### ISSUE TITLE
Client crash using copper armor when running Spongeforge.

### ISSUE THREAD

**Issue by ClaytonRayG** [MysticMods/MysticalWorld#196]
### General Information

**Describe the bug:**
Upon donning copper armor pieces, or holding in player hand, client is kicked from server. 

**To Reproduce:**
Attempt to utilize copper armor while on a server running SpongeForge.
Does not occur in single player.

**Mystic Mods Versions**
mysticalworld-1.12.2-1.9.1.jar
mysticallib-1.12.2-1.9.0.jar
Patchouli-1.0-21.jar

**Other Versions:**
- Forge: 1.12.2 - 14.23.5.2854
- Minecraft: 1.12.2
- SpongeForge 1.12.2-2838-7.2.3 & 1.12.2-2838-7.3.0: (Have tested multiple versions).

**Latest Server Log:**
(Log copied after player kick)

net.minecraft.util.ReportedException: Saving entity NBT
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1772) ~[vg.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75753_a(SaveHandler.java:184) [bfb.class:?]
	at net.minecraft.server.management.PlayerList.func_72391_b(PlayerList.java:348) [pl.class:?]
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:391) [pl.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:853) [pa.class:?]
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:453) [gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NoSuchMethodError: epicsquid.mysticalworld.item.ItemCopperArmor.func_185083_B_()Lnet/minecraft/inventory/EntityEquipmentSlot;
	at epicsquid.mysticalworld.item.ItemCopperArmor.getAttributeModifiers(ItemCopperArmor.java:26) ~[ItemCopperArmor.class:?]
	at net.minecraft.item.ItemStack.func_111283_C(ItemStack.java:1016) ~[aip.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70014_b(EntityLivingBase.java:513) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70014_b(EntityPlayer.java:935) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70014_b(EntityPlayerMP.java:246) ~[oq.class:?]
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1743) ~[vg.class:?]
	... 11 more

**Comment by ClaytonRayG** [comment]
I accidentally submitted 3 of these and don't know how to delete.
