### ISSUE TITLE
Player kick from forge server when attempting to use Copper Armor

### ISSUE THREAD

**Issue by ClaytonRayG** [MysticMods/MysticalWorld#198]
### General Information

**Describe the bug:**
Upon donning copper armor pieces, or holding in player hand, client is kicked from server. 

**To Reproduce:**
Attempt to utilize copper armor while on a server running Forge 1.12.2 version 2854 (and 2847).
Does not occur in single player.

**Mystic Mods Versions**
mysticalworld-1.12.2-1.9.1.jar
mysticallib-1.12.2-1.9.0.jar
Patchouli-1.0-21.jar

**Other Versions:**
- Forge: 1.12.2 - 14.23.5.2854
- Minecraft: 1.12.2

**Latest Server Log:**
(Log copied after player kick)

[15:33:00] [Server thread/WARN] [net.minecraft.network.NetworkSystem]: Failed to handle packet for /127.0.0.1:53999
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NoSuchMethodError: epicsquid.mysticalworld.item.ItemCopperArmor.func_185083_B_()Lnet/minecraft/inventory/EntityEquipmentSlot;
	at epicsquid.mysticalworld.item.ItemCopperArmor.getAttributeModifiers(ItemCopperArmor.java:26) ~[ItemCopperArmor.class:?]
	at net.minecraft.item.ItemStack.func_111283_C(ItemStack.java:1016) ~[aip.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2149) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
	... 9 more

**Comment by ClaytonRayG** [comment]
This is my first time submitting something to GitHub. Apologies for the multiple posts. Was trying to edit previous ones and somehow derped, submitting the edits as new issues.

**Comment by noobanidus** [comment]
So to my humiliation the "getEquipmentSlot" function is client-side-only in 1.12 which is something I didn't check for. I'll release an update shortly.

**Comment by noobanidus** [comment]
I believe this should be fixed in the most recent release.

**Comment by ClaytonRayG** [comment]
Dang that was quick! I'll test it within the next few hours and report back.

**Comment by ClaytonRayG** [comment]
That seems to have solved it. Updated to 1.9.2 on client and server. Modpack release has been updated for users. 

Thank you so much.
