### ISSUE TITLE
More lava cats problems 1.16.4 0.3.1.2 version

### ISSUE THREAD

**Issue by FurryApocalypse** [MysticMods/MysticalWorld#210]
So due there is not a single one cat in nether as was in previus issue we decided to spawn it with egg. Tamed cat dont wanna sit, dont even move when tamed  ( just stands and watchin) and when jumps to the water server is crashing every time ~~
Cat starts to move if other player hits him or his owner.
Problem seems to not occure with obsidian cat.
But whats funny if you throw obsidian cat to lava it turns in lava cat... what? (if that supposed to be then ok)

[21:16:50] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 8f140e68-ffb3-424c-b444-d05817d9fb1f
[21:16:50] [Server thread/ERROR] inecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:854) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:good_nights_sleep.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:good_nights_sleep.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:good_nights_sleep.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:good_nights_sleep.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201] {}
Caused by: java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
	at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111121_a(SourceFile:73) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_233767_b_(SourceFile:81) ~[?:?] {re:classloading}
	at epicsquid.mysticalworld.entity.LavaCatEntity.setIsLava(LavaCatEntity.java:288) ~ysticalworld:1.16.4-0.3.1.2] {re:classloading}
	at epicsquid.mysticalworld.entity.LavaCatEntity.func_70071_h_(LavaCatEntity.java:305) ~ysticalworld:1.16.4-0.3.1.2] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:good_nights_sleep.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	... 5 more

**Comment by noobanidus** [comment]
Whoops. I think I've fixed that now.
