### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by xshadowfox** [MysticMods/MysticalWorld#73]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.5.0.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 10/14/19 5:54 PM
Description: Initializing game

java.lang.NoClassDefFoundError: epicsquid/mysticalworld/materials/Gem
	at epicsquid.roots.init.ModVillagers.onProfessionRegister(ModVillagers.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_18_ModVillagers_onProfessionRegister_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: epicsquid.mysticalworld.materials.Gem
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at epicsquid.roots.init.ModVillagers.onProfessionRegister(ModVillagers.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_18_ModVillagers_onProfessionRegister_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 209622112 bytes (199 MB) / 771751936 bytes (736 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2844 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID            | Version       | Source                                        | Signature                                |
	|:----- |:------------- |:------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft     | 1.12.2        | minecraft.jar                                 | None                                     |
	| LCH   | mcp           | 9.42          | minecraft.jar                                 | None                                     |
	| LCH   | FML           | 8.0.99.99     | forge-1.12.2-14.23.5.2844.jar                 | None                                     |
	| LCH   | forge         | 14.23.5.2844  | forge-1.12.2-14.23.5.2844.jar                 | None                                     |
	| LCH   | dsurroundcore | 3.5.5.0       | minecraft.jar                                 | None                                     |
	| LCH   | biomesoplenty | 7.0.1.2441    | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar | None                                     |
	| LCH   | roots         | 1.12.2-3.0.12 | Roots-1.12.2-3.0.12.jar                       | None                                     |
	| LCH   | mysticalworld | 1.12.2-1.4.6  | MysticWorld-1.12.2-1.4.6.jar                  | None                                     |
	| LCH   | yurtmod       | 9.5.1         | NomadicTents-1.12.2-9.5.1.jar                 | None                                     |
	| LCH   | patchouli     | 1.0-20        | Patchouli-1.0-20.jar                          | None                                     |
	| LCH   | orelib        | 3.5.2.3       | OreLib-1.12.2-3.5.2.3.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dsurround     | 3.5.5.0       | DynamicSurroundings-1.12.2-3.5.5.0.jar        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | mysticallib   | 1.12.2-1.3.8  | mysticallib-1.12.2-1.3.8.jar                  | None                                     |

	Loaded coremods (and transformers): 
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.5.0.jar)
  org.orecruncher.dsurround.asm.Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.11' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2844
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.11, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz

**Comment by duely** [comment]
This turns out to be an issue with the way I've been writing the semvars for dependencies. It shouldn't happen again in the future; for now, just make sure you update Mystical World, Mystical Lib & Roots whenever you do an update.

In this case, it appears as though you have an out-dated version of either Roots or Mystic World installed. You'll want 3.0.16 or higher of Roots.
